name: cresca
description: A modern music streaming desktop application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  audio_session: ^0.1.25
  cached_network_image: 3.3.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  device_info_plus: ^9.1.1
  encrypt: ^5.0.3
  feedback: ^2.3.0
  file_picker: ^8.3.5
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8
  firebase_remote_config: ^4.3.8
  flutter:
    sdk: flutter
  flutter_appauth: ^8.0.3
  flutter_native_splash: ^2.3.10
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.17
  flutter_web_auth: ^0.6.0
  google_fonts: ^6.2.1
  http: ^1.1.0
  image_picker: ^1.1.2
  just_audio: ^0.9.35
  just_audio_background: ^0.0.1-beta.15
  just_audio_windows: ^0.2.2
  location: ^5.0.3
  marquee: ^2.3.0
  oauth2: ^2.0.3
  package_info_plus: ^4.2.0
  palette_generator: ^0.3.3+5
  permission_handler: ^11.3.0
  qr_flutter: ^4.1.0
  record: ^5.0.4
  rxdart: ^0.27.7
  sentry_flutter: ^7.13.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  supabase: ^2.6.2
  supabase_flutter: ^2.8.3
  system_tray: ^2.0.3
  uni_links: ^0.5.1
  url_launcher: ^6.2.2
  window_manager: ^0.3.8
  window_to_front: ^0.0.3
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_windows_video: ^1.0.11
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2
  crypto: ^3.0.3
  path: ^1.8.3

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  custom_lint: ^0.5.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  melos: ^4.1.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  rename_app: ^1.6.3
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - .env
    - assets/images/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: cresca
